doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Brand:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/domain/Brand/Entity'
                prefix: 'domain/Brand/Entity'
            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/domain/Order/Entity'
                prefix: 'domain/Order/Entity'
            Product:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/domain/Product/Entity'
                prefix: 'domain/Product/Entity'
            Tax:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/domain/Tax/Entity'
                prefix: 'domain/Tax/Entity'
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/domain/User/Entity'
                prefix: 'domain/User/Entity'
